import { client } from './sanity.client';
import type { AboutPage, HomePage } from './sanity.types';

export const aboutPageQuery = `*[_type == "aboutPage" && _id == "aboutPage"][0]{
  _id,
  title,
  slug,
  intro{
    heading1,
    heading2,
    heading3,
    description,
    ctaText,
    video{
      asset->{
        _id,
        url,
        originalFilename,
        mimeType,
        size
      }
    }
  },
  mission{
    title,
    content
  },
  values[]{
    title,
    description,
    icon
  },
  team{
    heading,
    members[]{
      name,
      role,
      bio,
      image{
        asset->{
          _id,
          url,
          metadata{
            dimensions{
              width,
              height
            }
          }
        }
      }
    }
  },
  seo{
    metaTitle,
    metaDescription,
    ogImage{
      asset->{
        _id,
        url
      }
    }
  }
}`;

export async function getAboutPage(): Promise<AboutPage | null> {
  return await client.fetch(aboutPageQuery);
}

export const homePageQuery = `*[_type == "homePage" && _id == "homePage"][0]{
  _id,
  title,
  slug,
  showReelsSection{
    image{
      asset->{
        _id,
        url,
        metadata{
          dimensions{ width, height }
        }
      }
    },
    video{
      asset->{
        _id,
        url,
        originalFilename,
        mimeType
      }
    }
  },
  heroSection{
    experienceBadge{
      icon{
        asset->{
          _id,
          url,
          metadata{
            dimensions{ width, height }
          }
        }
      },
      description
    },
    intro{
      heading,
      description
    },
    trustedBy{
      heading,
      logos[]{
        image{
          asset->{
            _id,
            url,
            metadata{
              dimensions{ width, height }
            }
          }
        },
        altText
      }
    }
  },
  awardWinningStudio{
    experienceBadge{
      icon{
        asset->{
          _id,
          url,
          metadata{
            dimensions{ width, height }
          }
        }
      },
      description
    },
    intro{
      heading,
      description
    },
    trustedBy{
      heading,
      logos[]{
        image{
          asset->{
            _id,
            url,
            metadata{
              dimensions{ width, height }
            }
          }
        },
        altText
      }
    },
    messageSection{
      textContent{
        backgroundText{
          asset->{
            _id,
            url,
            metadata{ dimensions{ width, height } }
          }
        },
        paragraph1,
        paragraph2,
        concludingStatement
      },
      image{
        asset->{
          _id,
          url,
          metadata{
            dimensions{ width, height }
          }
        }
      }
    }
  },
  digitalEcosystem{
    mainHeading,
    subheading{
      line1,
      line2
    },
    backgroundImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions{ width, height }
        }
      }
    },
    categories[]{
      title,
      description,
      style
    },
    services[]{
      name
    }
  },
  coherenceIsAlive{
    headline,
    image{
      asset->{
        _id,
        url,
        metadata{
          dimensions{ width, height }
        }
      }
    },
    subline,
    line1,
    items[]{
      image{
        asset->{
          _id,
          url,
          metadata{
            dimensions{ width, height }
          }
        }
      },
      label
    }
  },
  selectedWorks{
    heading,
    cards[]{
      title,
      image{
        asset->{
          _id,
          url,
          metadata{
            dimensions{ width, height }
          }
        }
      },
      client,
      narrative,
      index,
      href,
      scopeTags[]{
        name,
        color
      }
    }
  },
  diverseTeam{
    heading{
      prefix1,
      main1,
      prefix2,
      main2
    },
    backgroundImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions{ width, height }
        }
      }
    },
    teamMembers[]{
      name,
      color,
      positionX,
      positionY,
      arrowColor,
      arrowPositionX,
      arrowPositionY
    }
  },
  roiOfCoherence{
    heading,
    backgroundImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions{ width, height }
        }
      }
    },
    cards[]{
      heading,
      description,
      image{
        asset->{
          _id,
          url,
          metadata{
            dimensions{ width, height }
          }
        }
      }
    }
  },
  finalCta{
    heading,
    image{
      asset->{
        _id,
        url,
        metadata{
          dimensions{ width, height }
        }
      }
    },
    subheading,
    description,
    discoveryCall{
      label,
      href
    }
  },
  seo{
    metaTitle,
    metaDescription,
    ogImage{
      asset->{
        _id,
        url
      }
    }
  }
}`;

export async function getHomePage(): Promise<HomePage | null> {
  return await client.fetch(homePageQuery);
}

